### ISSUE TITLE
Add new variables for writehttp and collectdwin.config

### ISSUE THREAD

**Issue by tpoindessous** [kkzinger/kkzinger-collectdwin#2]
Hi

Could you be please add these variables in write_http ? 
* UserName 
* Password

They are explained in [https://github.com/bloomberg/collectdwin/wiki/WriteHttp-plugin#writehttp-plugin](https://github.com/bloomberg/collectdwin/wiki/WriteHttp-plugin#writehttp-plugin)

And since version 0.5.19, we can specify the HostName value in collectdwin.config. It is optional.

Could you please also add this feature ?

Thanks !

**Comment by kkzinger** [comment]
Hi,

I am currently not using collectdwin anymore. This is why I am not on track with the new features. I will look into it, could take a week or so.

**Comment by tpoindessous** [comment]
Hi

I did it in #3 and #4 .

Could you please take a look at these PR and if it looks good, could you release a new version and push it on the puppet forge ?

Thanks !

**Comment by tpoindessous** [comment]
Hi

I did find time to do some tests and my code was broken, so I corrected it.

Thanks !

**Comment by kkzinger** [comment]
Hi
Thank you for your work. I merged your PRs and will test it on our setup. After this I will publish it with new version to puppet forge.

**Comment by kkzinger** [comment]
Hi

Tests went good on my end and module is published with new version.
